sudo: required
services:
  - docker
before_script:
  - echo $SSH_KEY > ~/.ssh/my_aws_key.pem
script:
  - docker build -t cloud .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag cloud $DOCKER_USER/masterlemoncode_cloud
  - docker push $DOCKER_USER/masterlemoncode_cloud
  - ssh -i "~/.ssh/my_aws_key.pem" ec2-user@$HOST \
    "docker kill app && docker rmi mendrugory/masterlemoncode_cloud \
    && sudo docker run --rm -d -p 80:8080 --name app mendrugory/masterlemoncode_cloud"
